name: Build APK

on:
  workflow_dispatch:

jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ github.ref }}'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease -c settings.gradle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: '**/*.apk'